### PR TITLE
fix: remove invalid autocorrect attribute from textarea

### PR DESCRIPTION
**Pull request by mbrookes**
### Motivation

Fix an HTML validation error:

image

### Test plan

Use https://validator.w3.org/nu/

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]
The prop was added in 4cc6ca3ca88943997fe61d36eafc414909a59e1f. It seems to be non-standard for Safari: https://stackoverflow.com/questions/47985384/html-autocorrect-for-text-input-not-working. I expect this attribute to no longer be relevant.

**Comment by satya164** [comment]
> I expect this attribute to no longer be relevant.
@oliviertassinari why is that if safari still respects this attribute? did they remove support in recent versions?

**Comment by oliviertassinari** [comment]
@satya164 From what I understand, the prop is listed support for [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autocorrect) but not for [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea).

@mbrookes The alternative is to not render *react-simple-code-editor* in the initial SSR phase, it might actually improve hydration performance by doing less work.

**Comment by satya164** [comment]
@oliviertassinari gotcha

**Comment by mbrookes** [comment]
> From what I understand, the attribute autocorrect is supported for <input> but not for <textarea>.

Correct.

> The alternative is to not render react-simple-code-editor in the initial SSR phase

Sounds like we're going to need that anyway, but will leave this PR open for now.

**Comment by oliviertassinari** [comment]
Good for moving forward?

**Comment by oliviertassinari** [comment]
Actually, no, I have tested in iOS 12. It's still supported. It's a mess without. We need the attribute. I'm opening an issue in MDN and the HTML validator.

**Comment by oliviertassinari** [comment]
MDN: https://github.com/mdn/content/pull/2534

**Comment by oliviertassinari** [comment]
Validator: https://github.com/validator/validator/pull/1089

**Pull request closed without merging**
