### PR TITLE
Add react 17 support in peer dependencies.

### PR DESCRIPTION
**Pull request by jameshilliard**
Alternative to #83.

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]

**Comment by gajus** [comment]
@satya164 Any blockers for merging this?

**Comment by astutejoe** [comment]
pls for the love of Christ lol wtf

**Comment by wgarlock** [comment]
Any status update on this? I like the package, but I'll need to drop it if it's no longer being maintained.

**Comment by TomasLudvik** [comment]
Everything should be solved now, can you merge it and release new version please? @satya164

**Review by bernlarik — APPROVED** [review]

**Comment by marabesi** [comment]
Any news on this one? I would love to have it merged 😃

**Comment by gajus** [comment]
Has anyone created a fork of this?

**Comment by hanywang2** [comment]
Bump on having it merged. Would love to finally fix this dependency issue

**Comment by gajus** [comment]
For what it is worth, I ended up switching to Slate, there is even an example of how to do it.

https://www.slatejs.org/examples/code-highlighting

**Comment by stsmurf** [comment]
+1

**Comment by 0xalmanac** [comment]
+1

**Comment by satya164** [comment]
Thanks for the PR! I'm closing this since this is now fixed in main.

**Pull request closed without merging**
