### PR TITLE
chore: release 0.13.1

### PR DESCRIPTION
**Pull request by bharatkashyap**
When @oliviertassinari pushes directly on main, he gets the following error

Screenshot 2022-09-27 at 11 41 03
 
We need to open this PR to sync the main branch with https://www.npmjs.com/package/react-simple-code-editor/v/0.13.1.

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]

**Comment by satya164** [comment]
Hey @oliviertassinari, this isn't the correct way to release a new version. You have to run `yarn release`. I'm not sure why you can't push to `main` branch, but we can figure it out.

**Comment by oliviertassinari** [comment]
@satya164 Thanks for the help! `yarn release` went alright (the package was published on npm), and the tag was pushed but the last step failed (pushing the commit on the main branch).

**Comment by satya164** [comment]
@oliviertassinari doesn't look like it went alright since there's no release published on GitHub. we need to figure out the access and then I think it'd be best to publish another version.

**Comment by satya164** [comment]
@oliviertassinari I created an organization and invited you with owner access. you should have full access after accepting

**Comment by satya164** [comment]
so when you can, it would be good to run `yarn release` again so that it creates a release on GitHub.

**Comment by oliviertassinari** [comment]
Thanks! `yarn release` raises this warning:

> WARNING Latest version in registry (0.13.1) does not match package.json (0.13.0).

This was the logs the first time I ran the command:

Screenshot 2022-09-27 at 12 27 55

I feel that the simplest would be to replay the missing steps manually for v0.13.1.

**Comment by satya164** [comment]
@oliviertassinari feel free to do what's more comfortable for you now that you have full access - so should be able to create releases and push to main branch

**Comment by oliviertassinari** [comment]
@satya164 Done https://github.com/react-simple-code-editor/react-simple-code-editor/releases. I think that it's identical to a normal release;

**Pull request merged**
