### PR TITLE
docs: use hooks in README and add style import

### PR DESCRIPTION
**Pull request by nagayev**
This is my second attemption to fix README.
In the first I have broke commits' history.
Awaiting review from @caub 
### Motivation

Copy paste example didn't works

### CODE REVIEW

**Comment by caub** [comment]
@nagayev you could have used `git push -f` to keep the initial PR #64 where all the discussion was

**Comment by caub** [comment]
Thanks @nagayev, the PR looks all good to me

**Comment by nagayev** [comment]
> @nagayev you could have used `git push -f` to keep the initial PR #64 where all the discussion was
Yes, but I have broken the history
(actually I push HEAD~4 insted of HEAD~3)

**Comment by nagayev** [comment]
@caub Thanks for review!

**Review by oliviertassinari — APPROVED** [review]
I confirm it works: once moved to codesandbox https://codesandbox.io/s/gracious-river-6ld8w?file=/src/App.js:0-713

**Pull request merged**
