### PR TITLE
chore: provide a more up-to-date prismjs example

### PR DESCRIPTION
**Pull request by jannes-io**
Change the example code in README to be compatible with the latest prismjs function. Also use a function component rather than a class component to reduce complexity.

Additionally add the main prismjs css file since many issues arise from the lack of it in the example usage. (#58 #46 #16 )

### CODE REVIEW

**Comment by tomByrer** [comment]
I'm not sure why the `Class`-based example had to be overwritten?  I know arrow-functions are the new hipster way to React, but you could have just added it without removing the other example?

**Comment by jannes-io** [comment]
@tomByrer React function components and hooks are here to simplify and help React developers. We have completely transitioned to function based components and recommend anyone else to do so too. React documentation is moving to it and material-ui recently also converted all of their examples to function components.

Function components are not "the hipster way to React" but rather class based components are legacy and should only exist in your projects because you haven't gotten to refactoring them yet.

**Comment by jannes-io** [comment]
@satya164 could you please review? This PR has been open for over a month now.

**Comment by cyberbeast** [comment]
any updates on this PR? Could be extremely useful. :) @satya164

**Comment by jannes-io** [comment]
@cyberbeast pretty sure this repo is abandoned :(

**Comment by oliviertassinari** [comment]
Problem solved in https://github.com/satya164/react-simple-code-editor/pull/79

**Pull request closed without merging**
