### PR TITLE
fix: move style element to document head

### PR DESCRIPTION
**Pull request by mbrookes**
### Motivation

image

### Test plan

https://validator.w3.org/

### CODE REVIEW

**Comment by satya164** [comment]
This change has several issues:

1. Adding styles after mount means there'll be unstyled content before Javascript gets to execute and component finishes mounting, which is not desirable.
2. SSR will no longer work for the styles. With a style tag, it's automatic and requires no config.
3. This change never removes the styles after adding it. While it can be fixed, letting React manage it is much simpler.

I don't really care about making some validator happy. All browsers I have tested this in support this pattern, and not doing this only causes issues.

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
I agree, I don't think that this approach is ideal. How about we add an opt-in flag to remove the injection and export the styles as a variable? This way, developers that are willing to do the extra mile can move the style into the head, e.g. using emotion `Global` component can.

In the case of Material-UI, it's important that the output of https://validator.w3.org/ doesn't shallow issues with the components.

Alternatively @mbrookes did you consider not rendering react-simple-code-editor in the initial SSR output?

**Comment by oliviertassinari** [comment]
Also, note that `type="text/css"` is no longer encouraged. It can be removed.

**Comment by mbrookes** [comment]
satya164

1 & 2a: Since the CSS sets the font color of placeholder text for the underlying textfield, before which it's transparent, there's no FOUC or re-layout. What's the underlying concern?
2b: This doesn't require configuration?
3: That was a conscious decision.

@oliviertassinari 

> did you consider not rendering react-simple-code-editor in the initial SSR output?

"We add HTML validation warnings. [...] They can all be fixed in react-simple-code-editor"

So, no.

> How about we add an opt-in flag to remove the default <style> injection and export the styles as a variable? 

I don't think having a prop to enable rendering valid HTML, with the added dev overhead of injecting the styles locally, is a good tradeoff. NoSsr will do.

**Comment by oliviertassinari** [comment]
> What's the underlying concern?

From what I understand, the issue with the placeholder color is that, when the source is empty, the placeholder would flash at the hydration time.

**Comment by oliviertassinari** [comment]
How about we move the injection of the styles to did mount and only apply the inline style of `TextFillColor: 'transparent'` if the source is empty?

**Review by oliviertassinari — APPROVED** [review]

**Comment by satya164** [comment]
> Only IE would get a degraded experience.

While I understand that IE supprting IE is no longer a priority, IMO degrading the experience just to make a validator/linter happy is a reasonable tradeoff. Linters are supposed to be helpful to identify potential errors, not an be an authority over what to do.

Right now IE is a supported browser and the experience was as expected before the change. If we explicitly provide a degraded experience in a browser when we could avoid it, then we don't really support it.

Also keep in mind that many other projects use the package, and they might need to support IE (though I have no data), and this change will break their UX. So we need to be mindful of such breaking changes. What's not important for you maybe important for others.

How about we take another route? Keep the IE specific style in `<style>` tag and introduce a prop to not add the style (e.g. `ieSupport={true}` or something else) and note the prop in README with an explanation that it'll insert a `style` tag which will not pass the w3c validator. Maybe in next major release, the prop can be `false` by default and users would need to enable it explicitly if they want.

This will make the linter happy for your case, while also having an option to provide good UX for people who need IE support.

**Comment by oliviertassinari** [comment]
From my perspective, root of the issue is that body > style is not a great practice: https://github.com/whatwg/html/issues/1605#issuecomment-235956455, it's discouraged for the very same regression the current changes introduce for IE SSR users: FOUC. I would imagine this model targets an audience of developers, hence IE support is not important. The proposed approach with the boolean sounds great 👌

**Comment by satya164** [comment]
> it's discouraged for the very same regression the current changes introduce for IE SSR users: FOUC.

While generally it can be bad for performance, from my understanding, this isn't an issue in this particular case.

> I would imagine this package targets an audience of developers, hence IE support is not important

The thing is that it already supported IE properly, and we don't know if certain users realy on this. So regressing that would be a breaking change.

Anyway, let's add the prop for now.

**Comment by mbrookes** [comment]
> we don't know if certain users realy on this

Okay, let's take a step back here and be pragmatic. Nobody but _nobody_ who is using IE11, an 8 year old browser, cares a bit about, or will even notice, a tiny FOUC. Half the internet doesn't work for them already.

If it _really, really_ worries you that much, let's drop IE11 support entirely, and bump the major version. IE11 is EOS in eight months. Microsoft are dropping support for it in O365 in six. It's dead Jim.

**Comment by satya164** [comment]
> Nobody but nobody who is using IE11, an 8 year old browser, cares a bit about, or will even notice, a tiny FOUC.

Doesn't matter. I care about the quality of UX in projects I work on.

**Comment by mbrookes** [comment]
Sounds like you're saying you prefer option two?

**Comment by satya164** [comment]
I'd prefer not to drop support outright since it doesn't really take any work to maintain this and I would like to avoid breaking changes unless we have good reasons (e.g. maintainability etc.).

So I propose to introduce a prop which addresses both use cases: not do a breaking change, and also passes HTML validation for those who don't need IE support.

**Comment by satya164** [comment]
And if it causes more issues in future, then we should definitely drop support for IE and do a major version bump.

**Comment by mbrookes** [comment]
Just realised it's still version 0 anyway, so no need for a version bump for breaking changes according to SemVer. We can add the prop now, and could rip it out again in October with no qualms.

**Comment by oliviertassinari** [comment]
I do like the idea of degrading the experience for IE users, to create an incentive to upgrade. We have done that many times in Material-UI, basically a best effort. 

What we have done is that if the support comes with a non reasonable cost for modern browsers (here bundle size, mainly) we degrade the UX.

**Comment by satya164** [comment]
@oliviertassinari Personally I'd much prefer to just drop IE support instead of intentionally degrading the UX. If you strongly feel about not supporting IE then feel free to do a major release removing IE support.

**Comment by satya164** [comment]
Also, bundle size will not be affected here either way unless we drop support entirely.

**Comment by oliviertassinari** [comment]
> Also, bundle size will not be affected here either way unless we drop support entirely.

Do you mean not significantly? Removing the whole style and associated CSS will be less code.

I would personally add a prop and move to something else.

**Comment by satya164** [comment]
> Do you mean not significantly? Removing the whole style and associated CSS should be less code.

I mean this PR still keeps the CSS, so it won't change much. But removing whole style and associated CSS means dropping support entirely in which case it'd be a minor improvement.

**Comment by satya164** [comment]
> I would personally add a prop and move to something else. I don't think that the problem deserves a lot of attention.

Agreed. It's simplest solution and makes everyone happy.

**Comment by oliviertassinari** [comment]
Closing as it has been idle for over a year.

**Pull request closed without merging**
