### PR TITLE
Improve text selection experience

### PR DESCRIPTION
**Pull request by IJMacD**
### Motivation

Text selection looks janky if textarea is below marked up text.

This proposal swaps elements around so text selection looks more natural. 

### Test plan

No observed behavioural changes so far. Tested in latest Chrome.

### CODE REVIEW

**Review by satya164 — COMMENTED** [review]
Thanks for the PR. Can you provide a bit more details about the issue (like a small video of the difference)?

**Comment by IJMacD** [comment]
Here are a couple of screenshots illustrating the problem.

## Current stock implementation:

current implementation
When selecting text, the highlighted markup is in front of the native text-selection UI. This makes reading selected text difficult due to reduced contrast between foreground markup and text-selection background.

## After proposed change:

proposed implementation

Since the invisible `textarea` is now in front of the syntax highlighted text, the native selection UI is unobstructed. This makes it much easier to read text while selected.

**Comment by IJMacD** [comment]
The previous screenshots were Chrome/Windows but I'd expect the current behaviour to be identical on any platform. 

Here's a screenshot Firefox/Ubuntu.
image

**Comment by satya164** [comment]
> I'd expect the current behaviour to be identical on any platform

Text rendering works differently on each platform so I wouldn't expect that. This effect is not visible on Mac OS and looks very faint on Linux in the screenshot (though it's bad due to the selection color). 

Screen Shot 2022-08-09 at 20 31 38

I'll merge this since it looks better on Windows this way.

**Review by satya164 — APPROVED** [review]

**Pull request merged**
